baseURL = "https://rockchin.top"
languageCode = "zh-CN"
defaultContentLanguage = "zh-cn"
title = "RockChinQ"
theme = "paper"
enableInlineShortcodes = true
enableRobotsTXT = true
enableEmoji = true

[pagination]
  pagerSize = 20

[taxonomies]
  tag = "tags"

[params]
  color = 'linen'
  github = 'RockChinQ'
  linkedin = 'qinjunyan'
  avatar = 'rockchinq@gmail.com'
  name = 'Rock'
  bio = 'Thinking complicates, doing simplifies.'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "monokai"
    lineNos = false

[languages]
  [languages.zh-cn]
    weight = 1
    copyright = '© 2023-2026 RockChinQ'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "归档"
    url = "posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "tags/"
    weight = 20
